spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tools_db
    username: bazyan
    password: z11411985z
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration



